/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.io.File;
import java.sql.Connection;
import java.text.MessageFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import koneksi.koneksi1;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Muarif
 */
public class menu_utama extends javax.swing.JFrame {
    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        as = new javax.swing.JMenu();
        formsiswa = new javax.swing.JMenuItem();
        formbuku = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        formpeminjaman = new javax.swing.JMenuItem();
        formpengembalian = new javax.swing.JMenuItem();
        asa = new javax.swing.JMenu();
        laporansiswa = new javax.swing.JMenuItem();
        laporanbuku = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("APLIKASI PERPUSTAKAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 102));

        as.setText("Master");

        formsiswa.setText("Form Siswa");
        formsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formsiswaActionPerformed(evt);
            }
        });
        as.add(formsiswa);

        formbuku.setText("Form Buku");
        formbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formbukuActionPerformed(evt);
            }
        });
        as.add(formbuku);

        jMenuBar1.add(as);

        jMenu2.setText("Transaksi");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        formpeminjaman.setText("Form Peminjaman");
        formpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formpeminjamanActionPerformed(evt);
            }
        });
        jMenu2.add(formpeminjaman);

        formpengembalian.setText("Form Pengembalian");
        formpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formpengembalianActionPerformed(evt);
            }
        });
        jMenu2.add(formpengembalian);

        jMenuBar1.add(jMenu2);

        asa.setText("Laporan");

        laporansiswa.setText("Laporan Rekap Siswa");
        laporansiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporansiswaActionPerformed(evt);
            }
        });
        asa.add(laporansiswa);

        laporanbuku.setText("Laporan Rekap  Buku");
        laporanbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanbukuActionPerformed(evt);
            }
        });
        asa.add(laporanbuku);

        jMenuBar1.add(asa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formsiswaActionPerformed
        formsiswa formsiswa = new formsiswa();         
        formsiswa.setVisible(true); 
    }//GEN-LAST:event_formsiswaActionPerformed

    private void formbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formbukuActionPerformed
       formbuku formbuku = new formbuku();         
       formbuku.setVisible(true); 
    }//GEN-LAST:event_formbukuActionPerformed

    private void formpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formpeminjamanActionPerformed
        formpeminjaman formpeminjaman = new formpeminjaman();         
        formpeminjaman.setVisible(true);
    }//GEN-LAST:event_formpeminjamanActionPerformed

    private void laporansiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporansiswaActionPerformed
         try{
         String namaFile = "src/tampilan/laporan.jasper";
         Connection conn = new koneksi1().connect();
         HashMap parameter = new HashMap ();
         File report_file = new File(namaFile);
         JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
         JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
         JasperViewer.viewReport(jasperPrint, false);
         JasperViewer.setDefaultLookAndFeelDecorated(true);
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null,e.getMessage());
     }
    }//GEN-LAST:event_laporansiswaActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
      try{
         String namaFile = "src/tampilan/laporan_buku.jasper";
         Connection conn = new koneksi1().connect();
         HashMap parameter = new HashMap ();
         File report_file = new File(namaFile);
         JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
         JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
         JasperViewer.viewReport(jasperPrint, false);
         JasperViewer.setDefaultLookAndFeelDecorated(true);
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null,e.getMessage());
     }
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void formpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formpengembalianActionPerformed
      formpengembalian formpengembalian = new formpengembalian();         
      formpengembalian.setVisible(true);
    }//GEN-LAST:event_formpengembalianActionPerformed

    private void laporanbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanbukuActionPerformed
         try{
         String namaFile = "src/tampilan/laporan_buku.jasper";
         Connection conn = new koneksi1().connect();
         HashMap parameter = new HashMap ();
         File report_file = new File(namaFile);
         JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
         JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
         JasperViewer.viewReport(jasperPrint, false);
         JasperViewer.setDefaultLookAndFeelDecorated(true);
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null,e.getMessage());
     }
    }//GEN-LAST:event_laporanbukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu as;
    private javax.swing.JMenu asa;
    private javax.swing.JMenuItem formbuku;
    private javax.swing.JMenuItem formpeminjaman;
    private javax.swing.JMenuItem formpengembalian;
    private javax.swing.JMenuItem formsiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem laporanbuku;
    private javax.swing.JMenuItem laporansiswa;
    // End of variables declaration//GEN-END:variables
}
